### ISSUE TITLE
Error on MacOS/MAMP localhost

### ISSUE THREAD

**Issue by duksh** [leotiger/grav-plugin-backup-manager#8]
When clicked the 'Backup' button I got the error as attached
-----------------------------------------------------------------
<img width="866" alt="backup grav google chrome today at 19 44 35" src="https://cloud.githubusercontent.com/assets/586947/24714112/9e67ad66-1a38-11e7-9a78-a3743f25f59a.png">

**Comment by leotiger** [comment]
Thanks for reporting. Will have a look into this.

**Comment by leotiger** [comment]
Ok, should be caseinsensitive. This configuration option runs in from CLI. You see the message due to your PHP environment (and its settings) which scales this to be handled as an error. 

Background: This setting is not considered when working with the web interface. Inside of the web interface this is handled via a configuration option and can not be overwritten (like via CLI) for a single request.

I will push an update today or tomorrow.

**Comment by leotiger** [comment]
@duksh 

I've released v0.1.5 which should fix this issue.

**Comment by duksh** [comment]
@leotiger cheers mate
